# Generated by Django 6.1 on 2026-08-23 22:44

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "release_date",
                    models.DateField(
                        blank=True, default="", verbose_name="release date"
                    ),
                ),
                (
                    "is_partial",
                    models.BooleanField(default=False, verbose_name="is partial"),
                ),
                (
                    "translations",
                    models.JSONField(default=dict, verbose_name="translations"),
                ),
            ],
            options={
                "verbose_name": "Set",
                "verbose_name_plural": "Sets",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=10000, verbose_name="description"
                    ),
                ),
                (
                    "arena_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="arena ID"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="number")),
                ("index", models.PositiveSmallIntegerField(verbose_name="index")),
                (
                    "external_identifiers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="external identifiers",
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("mythic", "Mythic"),
                            ("special", "Special"),
                            ("bonus", "Bonus"),
                        ],
                        default="",
                        max_length=11,
                        verbose_name="rarity",
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("borderless", "Borderless"),
                        ],
                        max_length=10,
                        verbose_name="border color",
                    ),
                ),
                (
                    "available_finishes",
                    models.CharField(verbose_name="available finishes"),
                ),
                (
                    "available_frame_effects",
                    models.CharField(verbose_name="available frame effects"),
                ),
                (
                    "available_languages",
                    models.CharField(verbose_name="available languages"),
                ),
                (
                    "front_meta",
                    models.JSONField(default=dict, verbose_name="front meta"),
                ),
                (
                    "back_meta",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="back meta"
                    ),
                ),
                (
                    "front_versions",
                    models.JSONField(default=dict, verbose_name="front versions"),
                ),
                (
                    "back_versions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="back versions",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.artist",
                        verbose_name="artist",
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.set",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=10000,
                        verbose_name="description",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UID"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("ar", "Arabic"),
                            ("zh-cn", "Chinese simplified"),
                            ("zh-tw", "Chinese traditional"),
                            ("de", "German"),
                            ("he", "Hebrew"),
                            ("it", "Italian"),
                            ("jp", "Japanese"),
                            ("ko", "Korean"),
                            ("pr-br", "Portuguese (Brazil)"),
                            ("ru", "Russian"),
                            ("sa", "Sanskrit"),
                            ("es", "Spanish"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=5,
                        verbose_name="language",
                    ),
                ),
                (
                    "finish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nonfoil", "Non-foil"),
                            ("foil", "Foil"),
                            ("etched", "Etched"),
                            ("signed", "Signed"),
                        ],
                        default="",
                        max_length=7,
                        verbose_name="finish",
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("black", "Black"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("borderless", "Borderless"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="border color",
                    ),
                ),
                (
                    "frame_effect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("borderless", "Borderless"),
                            ("colorshifted", "Colorshifted"),
                            ("companion", "Companion"),
                            ("extendedart", "Extended art"),
                            ("fullart", "Full art"),
                            ("lesson", "Lesson"),
                            ("saga", "Saga"),
                            ("showcase", "Showcase"),
                            ("sunmoondfc", "Sun Moon"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="frame effect",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mt", "Mint"),
                            ("nm", "Near mint"),
                            ("ex", "Excellent"),
                            ("gd", "Good"),
                            ("lp", "Lightly played"),
                            ("pl", "Played"),
                            ("po", "Poor"),
                        ],
                        default="",
                        max_length=2,
                        verbose_name="condition",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="date added"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", max_length=10000, verbose_name="comment"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.card",
                        verbose_name="card",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.collection",
                        verbose_name="collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("cards", "CARDS")],
                        default="cards",
                        max_length=6,
                        verbose_name="type",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "version",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="version"
                    ),
                ),
                ("success", models.BooleanField(verbose_name="success")),
                (
                    "fail_details",
                    models.TextField(
                        blank=True, default="", verbose_name="fails details"
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(default=0, verbose_name="total items"),
                ),
            ],
            options={
                "verbose_name": "Import",
                "verbose_name_plural": "Imports",
                "unique_together": {("date", "type")},
            },
        ),
    ]
