# Generated by Django 6.1 on 2026-08-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="available_finishes",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="available finishes",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="available_frame_effects",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="available frame effects",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="available_languages",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="available languages",
            ),
        ),
    ]
