from magic_collector.api.schemas._schema_abstract import (
    META_SCHEMA,
    ROOT_SCHEMA,
    UUID_REGEX,
)

IMPORT_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/MTGJSONv5",
    "definitions": {
        "MTGJSONv5": ROOT_SCHEMA,
        "Meta": META_SCHEMA,
        "Data": {
            "type": "object",
            "patternProperties": {
                "^[0-9A-Z]{3}([0-9A-Z]{4})?$": {"$ref": "#/definitions/SetData"},
            },
            "title": "Data",
        },
        "SetData": {
            "type": "object",
            "properties": {
                "baseSetSize": {"type": "integer"},
                "block": {"type": "string"},
                "booster": {"type": "object"},
                "cards": {"type": "array", "items": {"$ref": "#/definitions/Card"}},
                "cardsphereSetId": {"type": "integer"},
                "code": {"type": "string"},
                "isFoilOnly": {"type": "boolean"},
                "isNonFoilOnly": {"type": "boolean"},
                "isOnlineOnly": {"type": "boolean"},
                "keyruneCode": {"type": "string"},
                "languages": {"type": "array"},
                "name": {"type": "string"},
                "releaseDate": {"type": "string", "format": "date"},
                "sealedProduct": {"type": "array"},
                "tcgplayerGroupId": {"type": "integer"},
                "tokens": {"type": "array"},
                "totalSetSize": {"type": "integer"},
                "translations": {"type": "object"},
                "type": {"type": "string"},
            },
            "required": [
                "cards",
                "code",
                "name",
                "releaseDate",
                "translations",
            ],
            "title": "SetData",
        },
        "Card": {
            "type": "object",
            "properties": {
                "artist": {"type": "string"},
                "artistIds": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": UUID_REGEX,
                    },
                },
                "availability": {"type": "array"},
                "boosterTypes": {"type": "array"},
                "borderColor": {"type": "string"},
                "colorIdentity": {"type": "array"},
                "colors": {"type": "array", "items": {"type": "string"}},
                "convertedManaCost": {"type": "number"},
                "edhrecRank": {"type": "integer"},
                "finishes": {"type": "array", "items": {"type": "string"}},
                "foreignData": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/ForeignData"},
                },
                "frameVersion": {"type": "string"},
                "hasFoil": {"type": "boolean"},
                "hasNonFoil": {"type": "boolean"},
                "identifiers": {"type": "object"},
                "keywords": {"type": "array", "items": {"type": "string"}},
                "language": {"type": "string"},
                "layout": {"type": "string"},
                "legalities": {"type": "object"},
                "manaCost": {"type": "string"},
                "manaValue": {"type": "number"},
                "name": {"type": "string"},
                "number": {"type": "string"},
                "originalText": {"type": "string"},
                "originalType": {"type": "string"},
                "printings": {"type": "array", "items": {"type": "string"}},
                "purchaseUrls": {"type": "object"},
                "rarity": {"type": "string"},
                "rulings": {"type": "array"},
                "setCode": {"type": "string"},
                "sourceProducts": {"type": "object"},
                "subtypes": {"type": "array", "items": {"type": "string"}},
                "supertypes": {"type": "array", "items": {"type": "string"}},
                "text": {"type": "string"},
                "type": {"type": "string"},
                "types": {"type": "array", "items": {"type": "string"}},
                "uuid": {
                    "type": "string",
                    "pattern": UUID_REGEX,
                },
            },
            "required": [
                "colors",
                "finishes",
                "foreignData",
                "identifiers",
                "layout",
                "manaValue",
                "name",
                "number",
                "rarity",
                "subtypes",
                "supertypes",
                "types",
                "uuid",
            ],
            "title": "Card",
        },
        "ForeignData": {
            "type": "object",
            "properties": {
                "flavorText": {"type": "string"},
                "identifiers": {"type": "object"},
                "language": {"type": "string"},
                "multiverseId": {"type": "integer"},
                "name": {"type": "string"},
                "text": {"type": "string"},
                "type": {"type": "string"},
            },
            "title": "ForeignData",
        },
    },
}
